### ISSUE TITLE
Missing license

### ISSUE THREAD

**Issue by davidscn** [davydden/large-strain-matrix-free#110]
I was using and I am still using code based on this work. My initial commit is essentially a fork of this repository. In my code repository, I stick to the (more or less deal.II-standard ?) license LGPL 3.1. However, I noticed that the code I was using (namely from this project) does not specify any license and therefore, I don't have the permission to do what I did, namely copying. I am not sure if this is intended and I would like to ask if it would be possible to add a license. Otherwise, I should delete my code or change the licensing to something appropriate.

**Comment by kronbichler** [comment]
I think we wanted to publish this as LGPL-licensed code. I hereby give my consent to publish the code under the LGPL 3.1 license. Let's here what the other contributors, @masterleinad @jppelteret @davydden, think.

**Comment by masterleinad** [comment]
I agree and give my consent.

**Comment by davydden** [comment]
Agree as well with LGPL 3.1

**Comment by jppelteret** [comment]
Yes, I also agree with LGPL 3.1.

**Comment by davidscn** [comment]
Great! Does any of the main authors (with repository ownership) wants to take care of this or should I open a pull request?

**Comment by davidscn** [comment]
Thank you!
